### ISSUE TITLE
Error message when copying dates and sources to all queries

### ISSUE THREAD

**Issue by AnissaPierre** [mitmedialab/MediaCloud-Web-Tools#1588]
<img width="1372" alt="Screen Shot 2019-06-04 at 9 43 07 AM" src="https://user-images.githubusercontent.com/25494330/58883869-48c75d00-86ad-11e9-8a63-35160816d823.png">

**Comment by AnissaPierre** [comment]
It works if you do a hard refresh

**Comment by cindyloo** [comment]
allowing the user to click off of a newly created query with no name and/or no media causes some problems. We used to disallow this, but perhaps we now allow it in order to take advantage of this copy all capability. Clicking back and forth causes a few bugs I'm digging into. Associated with the copying of other data too
